### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by davidryan59** [davidryan59/ji-rcn#6]
Check if the specs make it into the bundle.js file? They are currently 10kB.

If so, consider using an .npmignore file to exclude them. Check interactions between .gitignore and .npmignore first.

**Comment by daveryan23** [comment]
After reading the documentation, it appears that if you have an .npmignore, you need to copy in most of the stuff in .gitignore...

**Comment by davidryan59** [comment]
Tests are no longer in the npm package, but they are retained in GitLab. This has been achieved using separate .npmignore and .gitignore files.
